#import "TPComposerController.h"
#import "TPTranslationService.h"
#import <objc/runtime.h>
static const void*TPComposerButtonKey=&TPComposerButtonKey,*TPComposerViewKey=&TPComposerViewKey,*TPComposerChatKey=&TPComposerChatKey;
@implementation TPComposerController
+(instancetype)shared{static id x;static dispatch_once_t o;dispatch_once(&o,^{x=[self new];});return x;}
-(void)attachToComposer:(UITextView*)composer chatId:(NSString*)chatId{if(!composer.superview||objc_getAssociatedObject(composer,TPComposerButtonKey))return;UIButton*b=[UIButton buttonWithType:UIButtonTypeSystem];b.accessibilityLabel=@"翻译输入内容";[b setTitle:@"译" forState:UIControlStateNormal];b.titleLabel.font=[UIFont boldSystemFontOfSize:15];if(@available(iOS 13,*)){b.backgroundColor=UIColor.tertiarySystemFillColor;b.tintColor=UIColor.systemGreenColor;}else b.backgroundColor=[UIColor colorWithWhite:.9 alpha:.9];b.layer.cornerRadius=15;[b addTarget:self action:@selector(translate:) forControlEvents:UIControlEventTouchUpInside];[composer.superview addSubview:b];b.translatesAutoresizingMaskIntoConstraints=NO;[NSLayoutConstraint activateConstraints:@[[b.widthAnchor constraintEqualToConstant:30],[b.heightAnchor constraintEqualToConstant:30],[b.leadingAnchor constraintEqualToAnchor:composer.leadingAnchor constant:5],[b.centerYAnchor constraintEqualToAnchor:composer.centerYAnchor]]];composer.textContainerInset=UIEdgeInsetsMake(composer.textContainerInset.top,MAX(composer.textContainerInset.left,39),composer.textContainerInset.bottom,composer.textContainerInset.right);objc_setAssociatedObject(composer,TPComposerButtonKey,b,OBJC_ASSOCIATION_RETAIN_NONATOMIC);objc_setAssociatedObject(b,TPComposerViewKey,[NSValue valueWithNonretainedObject:composer],OBJC_ASSOCIATION_RETAIN_NONATOMIC);objc_setAssociatedObject(b,TPComposerChatKey,chatId?:@"manual",OBJC_ASSOCIATION_COPY_NONATOMIC);}
-(BOOL)containsChinese:(NSString*)text{for(NSUInteger i=0;i<text.length;i++){unichar c=[text characterAtIndex:i];if(c>=0x4E00&&c<=0x9FFF)return YES;}return NO;}
-(void)translate:(UIButton*)button{UITextView*composer=[objc_getAssociatedObject(button,TPComposerViewKey) nonretainedObjectValue];NSString*text=[composer.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(!composer||!text.length)return;NSString*target=[self containsChinese:text]?@"English":@"zh-CN";button.enabled=NO;[button setTitle:@"…" forState:UIControlStateNormal];[TPTranslationService translate:text target:target chatId:objc_getAssociatedObject(button,TPComposerChatKey) completion:^(NSString*result,NSError*error){button.enabled=YES;[button setTitle:@"译" forState:UIControlStateNormal];if(result.length){composer.text=result;if([composer.delegate respondsToSelector:@selector(textViewDidChange:)])[composer.delegate textViewDidChange:composer];}else [self showError:error.localizedDescription?:@"翻译失败"]; }];}
-(void)showError:(NSString*)message{UIWindow*w;for(UIWindow*x in UIApplication.sharedApplication.windows)if(x.isKeyWindow)w=x;UIViewController*v=w.rootViewController;while(v.presentedViewController)v=v.presentedViewController;UIAlertController*a=[UIAlertController alertControllerWithTitle:@"翻译失败" message:message preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"好" style:0 handler:nil]];[v presentViewController:a animated:YES completion:nil];}
@end
