#import "TPMessageTextExtractor.h"
#import "TPLanguageDetector.h"
#import <CommonCrypto/CommonDigest.h>
@implementation TPExtractedMessage @end
@implementation TPMessageTextExtractor
+(NSString*)messagePartFromMixedAccessibility:(NSString*)value{NSString*t=[value stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if([TPLanguageDetector shouldTranslateText:t])return t;NSCharacterSet*separators=[NSCharacterSet characterSetWithCharactersInString:@",，\n|•"];NSString*best=nil;for(NSString*part in [t componentsSeparatedByCharactersInSet:separators]){NSString*p=[part stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if([TPLanguageDetector shouldTranslateText:p]&&p.length>best.length)best=p;}return best;}
+(void)addText:(NSString*)value view:(UIView*)view font:(CGFloat)font into:(NSMutableArray*)a{NSString*t=[self messagePartFromMixedAccessibility:value];if(t.length)[a addObject:@{@"view":view,@"text":t,@"font":@(font)}];}
+(void)collect:(UIView*)v into:(NSMutableArray*)a{if([v.accessibilityIdentifier isEqualToString:@"tp.translation"])return;if([v isKindOfClass:UILabel.class]){[self addText:((UILabel*)v).text view:v font:((UILabel*)v).font.pointSize into:a];}else if([v isKindOfClass:UITextView.class]){[self addText:((UITextView*)v).text view:v font:((UITextView*)v).font.pointSize into:a];}else if(v.subviews.count==0||v.isAccessibilityElement){[self addText:v.accessibilityLabel view:v font:15 into:a];[self addText:v.accessibilityValue view:v font:14 into:a];}for(UIView*s in v.subviews)[self collect:s into:a];}
+(NSString*)hash:(NSString*)s{NSData*d=[s dataUsingEncoding:NSUTF8StringEncoding];unsigned char o[CC_SHA256_DIGEST_LENGTH];CC_SHA256(d.bytes,(CC_LONG)d.length,o);NSMutableString*r=[NSMutableString string];for(int i=0;i<8;i++)[r appendFormat:@"%02x",o[i]];return r;}
+(TPExtractedMessage*)extractFromCell:(UIView*)cell inRoot:(UIView*)root{NSMutableArray*a=[NSMutableArray array];[self collect:cell into:a];NSDictionary*best;CGFloat score=0;for(NSDictionary*x in a){NSString*t=x[@"text"];CGFloat s=MIN(t.length,200)+[x[@"font"]doubleValue]*5;if(s>score){score=s;best=x;}}NSString*text=best[@"text"];UIView*source=best[@"view"];if(!text.length){NSString*t=[cell.accessibilityLabel stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if([TPLanguageDetector shouldTranslateText:t]){text=t;source=cell;}}if(!text.length)return nil;CGRect r=[source convertRect:source.bounds toView:root];TPExtractedMessage*m=[TPExtractedMessage new];m.text=text;m.sourceView=source;m.cell=cell;m.outgoing=CGRectGetMidX(r)>CGRectGetWidth(root.bounds)*.55;m.messageId=[self hash:[NSString stringWithFormat:@"%@|%.0f|%@",m.outgoing?@"out":@"in",CGRectGetMinY([cell convertRect:cell.bounds toView:root]),text]];return m;}
@end
