#import "TPMessageScanner.h"
#import "TPMessageTextExtractor.h"
#import "TPTranslationRenderer.h"
#import "TPTranslationService.h"
#import "TPSettings.h"
#import "TPDebugLogger.h"
#import <objc/runtime.h>
static const void*TPMessageIdentityKey=&TPMessageIdentityKey;
@implementation TPMessageScanner
+(instancetype)shared{static id x;static dispatch_once_t o;dispatch_once(&o,^{x=[self new];});return x;}
-(void)collectCells:(UIView*)v into:(NSMutableArray*)a{NSString*n=NSStringFromClass(v.class).lowercaseString;BOOL native=[v isKindOfClass:UITableViewCell.class]||[v isKindOfClass:UICollectionViewCell.class];BOOL custom=([n containsString:@"message"]||[n containsString:@"chatcell"]||[n containsString:@"bubblecell"])&&CGRectGetHeight(v.bounds)>=20&&CGRectGetHeight(v.bounds)<600;if(native||custom){if(v.window&&!v.hidden&&v.alpha>.1)[a addObject:v];if(native)return;}for(UIView*s in v.subviews)[self collectCells:s into:a];}
-(void)scanRoot:(UIView*)root composer:(UITextView*)composer chatId:(NSString*)chat{TPSettings*s=TPSettings.shared;if(!s.autoTranslate||!s.autoScanVisibleMessages||!root.window||!composer.window)return;NSMutableArray*cells=[NSMutableArray array];[self collectCells:root into:cells];NSInteger candidates=0,queued=0,skippedOutgoing=0;CGRect input=[composer convertRect:composer.bounds toView:root];for(UIView*cell in cells){CGRect r=[cell convertRect:cell.bounds toView:root];if(!CGRectIntersectsRect(r,root.bounds)||CGRectGetMinY(r)>=CGRectGetMinY(input))continue;TPExtractedMessage*m=[TPMessageTextExtractor extractFromCell:cell inRoot:root];if(!m)continue;candidates++;if(m.outgoing&&!s.translateOutgoing){skippedOutgoing++;continue;}NSString*prior=objc_getAssociatedObject(cell,TPMessageIdentityKey);if(prior&&![prior isEqualToString:m.messageId]){[TPTranslationRenderer resetCell:cell];objc_setAssociatedObject(cell,TPMessageIdentityKey,nil,OBJC_ASSOCIATION_COPY_NONATOMIC);}if([prior isEqualToString:m.messageId]&&[TPTranslationRenderer stateForCell:cell]!=TPBubbleStateUnprocessed)continue;objc_setAssociatedObject(cell,TPMessageIdentityKey,m.messageId,OBJC_ASSOCIATION_COPY_NONATOMIC);queued++;[self translate:m chat:chat];}NSString*summary=[NSString stringWithFormat:@"chat=%@ cells=%lu candidates=%ld queued=%ld skippedOutgoing=%ld",(chat?:@"unknown"),(unsigned long)cells.count,(long)candidates,(long)queued,(long)skippedOutgoing];if(![TPDebugLogger.shared.scanSummary isEqualToString:summary]){TPDebugLogger.shared.scanSummary=summary;[TPDebugLogger.shared log:[@"scan " stringByAppendingString:summary]];}else TPDebugLogger.shared.scanSummary=summary;}
-(void)translate:(TPExtractedMessage*)m chat:(NSString*)chat{[TPTranslationRenderer setTranslatingForMessage:m];__weak typeof(self)w=self;[TPTranslationService translate:m.text chatId:chat completion:^(NSString*t,NSError*e){if(t.length)[TPTranslationRenderer setTranslation:t forMessage:m];else{TPDebugLogger.shared.lastError=e.localizedDescription;[TPTranslationRenderer setFailure:e forMessage:m retry:^{[w translate:m chat:chat];}];}}];}
@end
