#import "TPMessageScanner.h"
#import "TPTranslationService.h"
#import <objc/runtime.h>
static const void *TPSourceKey=&TPSourceKey, *TPTranslationKey=&TPTranslationKey, *TPPendingKey=&TPPendingKey;
@implementation TPMessageScanner
+ (instancetype)shared { static id x; static dispatch_once_t o; dispatch_once(&o,^{x=[self new];}); return x; }
- (BOOL)isCandidate:(UILabel *)label root:(UIView *)root composer:(UITextView *)composer {
  NSString *t=[label.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; if(t.length<2||t.length>600||label.hidden||label.alpha<0.1||!label.window)return NO;
  if(objc_getAssociatedObject(label,TPTranslationKey)||[label.accessibilityIdentifier isEqualToString:@"tp.translation"])return NO;
  if(composer && ([label isDescendantOfView:composer]||[composer isDescendantOfView:label.superview]))return NO;
  CGRect r=[label convertRect:label.bounds toView:root]; if(CGRectGetMaxY(r)>CGRectGetMinY([composer convertRect:composer.bounds toView:root])+4)return NO;
  if(t.length<=8 && ([t containsString:@":"]||[t isEqualToString:@"Yesterday"]||[t isEqualToString:@"Today"]))return NO;
  return CGRectIntersectsRect(r,root.bounds);
}
- (void)collect:(UIView *)v root:(UIView *)root composer:(UITextView *)composer output:(NSMutableArray *)out { if([v isKindOfClass:UILabel.class]&&[self isCandidate:(UILabel*)v root:root composer:composer])[out addObject:v]; for(UIView *s in v.subviews)[self collect:s root:root composer:composer output:out]; }
- (void)scanVisibleMessagesInView:(UIView *)root excludingComposer:(UITextView *)composer { if(!root.window||!composer)return; NSMutableArray *labels=[NSMutableArray array]; [self collect:root root:root composer:composer output:labels]; for(UILabel *l in labels)[self translateLabel:l]; }
- (void)translateLabel:(UILabel *)source { NSString *text=[source.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]; NSString *old=objc_getAssociatedObject(source,TPSourceKey); if([old isEqualToString:text]&&(objc_getAssociatedObject(source,TPTranslationKey)||objc_getAssociatedObject(source,TPPendingKey)))return; UILabel *previous=objc_getAssociatedObject(source,TPTranslationKey); [previous removeFromSuperview]; objc_setAssociatedObject(source,TPTranslationKey,nil,OBJC_ASSOCIATION_RETAIN_NONATOMIC); objc_setAssociatedObject(source,TPSourceKey,text,OBJC_ASSOCIATION_COPY_NONATOMIC); objc_setAssociatedObject(source,TPPendingKey,@YES,OBJC_ASSOCIATION_RETAIN_NONATOMIC); NSString *target=[TPTranslationService automaticTargetForText:text]; __weak UILabel *weakSource=source; [TPTranslationService translate:text target:target completion:^(NSString *result,NSError *error){ UILabel *s=weakSource; objc_setAssociatedObject(s,TPPendingKey,nil,OBJC_ASSOCIATION_RETAIN_NONATOMIC); if(!s.window||!result.length||![objc_getAssociatedObject(s,TPSourceKey)isEqualToString:text])return; [self showTranslation:result below:s]; }]; }
- (void)showTranslation:(NSString *)text below:(UILabel *)source { UIView *container=source.superview; if(!container)return; UILabel *translation=[UILabel new]; translation.accessibilityIdentifier=@"tp.translation"; translation.text=text; translation.numberOfLines=0; translation.font=[UIFont systemFontOfSize:11]; translation.textColor=[UIColor colorWithRed:.25 green:.55 blue:.45 alpha:1]; translation.backgroundColor=[UIColor colorWithWhite:1 alpha:.72]; translation.layer.cornerRadius=3; translation.clipsToBounds=YES; CGSize max=CGSizeMake(MAX(120,CGRectGetWidth(source.bounds)),60); CGSize size=[translation sizeThatFits:max]; translation.frame=CGRectMake(CGRectGetMinX(source.frame),CGRectGetMaxY(source.frame)+2,MIN(max.width,size.width+6),MIN(60,size.height+4)); translation.autoresizingMask=UIViewAutoresizingFlexibleTopMargin|UIViewAutoresizingFlexibleRightMargin; container.clipsToBounds=NO; [container addSubview:translation]; objc_setAssociatedObject(source,TPTranslationKey,translation,OBJC_ASSOCIATION_RETAIN_NONATOMIC); }
@end
