#import "TPMessageTextExtractor.h"
#import "TPLanguageDetector.h"
#import <CommonCrypto/CommonDigest.h>
@implementation TPExtractedMessage @end
@implementation TPMessageTextExtractor
+(void)collect:(UIView*)v into:(NSMutableArray*)a{if([v.accessibilityIdentifier isEqualToString:@"tp.translation"])return;if([v isKindOfClass:UILabel.class]||[v isKindOfClass:UITextView.class]){NSString*t=[v isKindOfClass:UILabel.class]?((UILabel*)v).text:((UITextView*)v).text;t=[t stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if([TPLanguageDetector shouldTranslateText:t])[a addObject:@{ @"view":v,@"text":t,@"font":@([v isKindOfClass:UILabel.class]?((UILabel*)v).font.pointSize:((UITextView*)v).font.pointSize)}];}for(UIView*s in v.subviews)[self collect:s into:a];}
+(NSString*)hash:(NSString*)s{NSData*d=[s dataUsingEncoding:NSUTF8StringEncoding];unsigned char o[CC_SHA256_DIGEST_LENGTH];CC_SHA256(d.bytes,(CC_LONG)d.length,o);NSMutableString*r=[NSMutableString string];for(int i=0;i<8;i++)[r appendFormat:@"%02x",o[i]];return r;}
+(TPExtractedMessage*)extractFromCell:(UIView*)cell inRoot:(UIView*)root{NSMutableArray*a=[NSMutableArray array];[self collect:cell into:a];NSDictionary*best;CGFloat score=0;for(NSDictionary*x in a){NSString*t=x[@"text"];CGFloat s=MIN(t.length,200)+[x[@"font"]doubleValue]*5;if(s>score){score=s;best=x;}}NSString*text=best[@"text"];UIView*source=best[@"view"];if(!text.length){NSString*t=[cell.accessibilityLabel stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if([TPLanguageDetector shouldTranslateText:t]){text=t;source=cell;}}if(!text.length)return nil;CGRect r=[source convertRect:source.bounds toView:root];TPExtractedMessage*m=[TPExtractedMessage new];m.text=text;m.sourceView=source;m.cell=cell;m.outgoing=CGRectGetMidX(r)>CGRectGetWidth(root.bounds)*.55;m.messageId=[self hash:[NSString stringWithFormat:@"%@|%.0f|%@",m.outgoing?@"out":@"in",CGRectGetMinY([cell convertRect:cell.bounds toView:root]),text]];return m;}
@end
