#import "TPPluginSettingsPage.h"
#import "TPSettings.h"
#import "TPCacheStore.h"
#import "TPTermbaseManager.h"
#import "TPTranslationService.h"
#import "TPDebugLogger.h"
#import "TPChatPageObserver.h"
#import "TPThemeAdapter.h"

@interface TPTermEditor:UIViewController @property(nonatomic,strong)UITextView*textView; @end
@implementation TPTermEditor
-(void)viewDidLoad{[super viewDidLoad];self.title=@"术语库";self.view.backgroundColor=TPThemeAdapter.background;self.textView=[[UITextView alloc]initWithFrame:self.view.bounds];self.textView.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;self.textView.font=[UIFont monospacedSystemFontOfSize:14 weight:UIFontWeightRegular];NSMutableArray*a=[NSMutableArray array];[TPTermbaseManager.shared.terms enumerateKeysAndObjectsUsingBlock:^(id k,id v,BOOL*stop){[a addObject:[NSString stringWithFormat:@"%@ = %@",k,v]];}];self.textView.text=[a componentsJoinedByString:@"\n"];[self.view addSubview:self.textView];self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemSave target:self action:@selector(save)];}
-(void)save{NSMutableDictionary*old=[TPTermbaseManager.shared.terms mutableCopy];for(NSString*k in old.allKeys)[TPTermbaseManager.shared removeSource:k];for(NSString*line in [self.textView.text componentsSeparatedByCharactersInSet:NSCharacterSet.newlineCharacterSet]){NSRange r=[line rangeOfString:@"="];if(r.location==NSNotFound)continue;NSString*s=[[line substringToIndex:r.location]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceCharacterSet];NSString*t=[[line substringFromIndex:r.location+1]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceCharacterSet];[TPTermbaseManager.shared setTarget:t forSource:s];}[self.navigationController popViewControllerAnimated:YES];}
@end

@interface TPDebugLogViewer:UIViewController @property(nonatomic,strong)UITextView*textView; @end
@implementation TPDebugLogViewer
-(void)viewDidLoad{[super viewDidLoad];self.title=@"调试日志";self.view.backgroundColor=TPThemeAdapter.background;self.textView=[[UITextView alloc]initWithFrame:self.view.bounds];self.textView.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;self.textView.editable=NO;self.textView.selectable=YES;self.textView.alwaysBounceVertical=YES;self.textView.font=[UIFont monospacedSystemFontOfSize:12 weight:UIFontWeightRegular];self.textView.text=TPDebugLogger.shared.exportText?:@"";[self.view addSubview:self.textView];self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithTitle:@"复制" style:UIBarButtonItemStylePlain target:self action:@selector(copyLog)];}
-(void)copyLog{NSString*text=self.textView.text?:@"";UIPasteboard.generalPasteboard.string=text;[UIPasteboard.generalPasteboard setItems:@[@{@"public.utf8-plain-text":text}]];UIAlertController*a=[UIAlertController alertControllerWithTitle:@"调试日志" message:[NSString stringWithFormat:@"已复制 %lu 字符",(unsigned long)text.length] preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"好" style:0 handler:nil]];[self presentViewController:a animated:YES completion:nil];}
@end

@interface TPPluginSettingsPage()@property(nonatomic,strong)NSArray*rows;@end
@implementation TPPluginSettingsPage
-(void)viewDidLoad{[super viewDidLoad];self.title=@"翻译插件设置";self.rows=@[@[@"自动翻译接收消息",@"只翻译对方消息",@"翻译自己发送的消息",@"显示“译文：”前缀",@"失败时显示重试",@"进入聊天自动扫描"],@[@"目标语言",@"源语言识别",@"跳过中文消息"],@[@"Provider",@"Base URL",@"API Key",@"Model Name",@"请求超时时间",@"最大重试次数",@"测试翻译"],@[@"翻译风格"],@[@"启用术语库",@"编辑术语库"],@[@"启用翻译缓存",@"清空当前聊天缓存",@"清空全部缓存",@"缓存统计"],@[@"插件状态",@"页面识别状态",@"当前聊天页",@"当前设置页",@"最近错误",@"当前 Provider / 模型",@"最近请求耗时",@"调试日志",@"查看调试日志"]];self.navigationItem.leftBarButtonItem=self.presentingViewController?[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemClose target:self action:@selector(close)]:nil;[NSNotificationCenter.defaultCenter addObserver:self selector:@selector(reload) name:TPSettingsDidChangeNotification object:nil];}
-(void)dealloc{[NSNotificationCenter.defaultCenter removeObserver:self];}
-(void)close{[self dismissViewControllerAnimated:YES completion:nil];}-(void)reload{[self.tableView reloadData];}
-(NSUInteger)copyDebugLogToPasteboard{NSString*text=TPDebugLogger.shared.exportText?:@"";if(!text.length)text=[NSString stringWithFormat:@"TranslatePlugin debug export empty at %@",NSDate.date];UIPasteboard*pb=UIPasteboard.generalPasteboard;pb.string=text;[pb setItems:@[@{@"public.utf8-plain-text":text}]];[TPDebugLogger.shared log:[NSString stringWithFormat:@"debug log copied chars=%lu",(unsigned long)text.length]];return text.length;}
-(NSInteger)numberOfSectionsInTableView:(UITableView*)t{return self.rows.count;}-(NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return [self.rows[s]count];}
-(NSString*)tableView:(UITableView*)t titleForHeaderInSection:(NSInteger)s{return @[@"基础设置",@"语言设置",@"API 设置",@"翻译风格",@"术语库",@"缓存管理",@"调试信息"][s];}
-(UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)p{UITableViewCell*c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:nil];c.textLabel.text=self.rows[p.section][p.row];c.textLabel.adjustsFontSizeToFitWidth=YES;TPSettings*s=TPSettings.shared;if([self isSwitch:p]){UISwitch*sw=[UISwitch new];sw.on=[self switchValue:p settings:s];sw.tag=p.section*100+p.row;[sw addTarget:self action:@selector(switchChanged:) forControlEvents:UIControlEventValueChanged];c.accessoryView=sw;}else{c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;c.detailTextLabel.text=[self detail:p settings:s];}if(p.section==6)c.accessoryType=UITableViewCellAccessoryNone;return c;}
-(BOOL)isSwitch:(NSIndexPath*)p{return(p.section==0)||(p.section==1&&p.row==2)||(p.section==4&&p.row==0)||(p.section==5&&p.row==0)||(p.section==6&&p.row==7);}
-(BOOL)switchValue:(NSIndexPath*)p settings:(TPSettings*)s{if(p.section==0)return [(NSNumber*)@[@(s.autoTranslate),@(s.translateIncomingOnly),@(s.translateOutgoing),@(s.showTranslationPrefix),@(s.showRetryOnFailure),@(s.autoScanVisibleMessages)][p.row] boolValue];if(p.section==1)return s.skipChineseMessages;if(p.section==4)return s.enableTermbase;if(p.section==5)return s.enableCache;return s.debugLogEnabled;}
-(void)switchChanged:(UISwitch*)sw{NSInteger s=sw.tag/100,r=sw.tag%100;TPSettings*x=TPSettings.shared;if(s==0){switch(r){case 0:x.autoTranslate=sw.on;break;case 1:x.translateIncomingOnly=sw.on;if(sw.on)x.translateOutgoing=NO;break;case 2:x.translateOutgoing=sw.on;if(sw.on)x.translateIncomingOnly=NO;break;case 3:x.showTranslationPrefix=sw.on;break;case 4:x.showRetryOnFailure=sw.on;break;case 5:x.autoScanVisibleMessages=sw.on;break;}[self.tableView reloadData];}else if(s==1)x.skipChineseMessages=sw.on;else if(s==4)x.enableTermbase=sw.on;else if(s==5)x.enableCache=sw.on;else if(s==6)x.debugLogEnabled=sw.on;}
-(NSString*)detail:(NSIndexPath*)p settings:(TPSettings*)s{if(p.section==1)return p.row==0?@"简体中文":@"自动";if(p.section==2){return @[s.provider,s.baseURL.length?s.baseURL:@"未设置",s.apiKey.length?@"••••••••":@"未设置",s.model.length?s.model:@"未设置",[NSString stringWithFormat:@"%.0f 秒",s.timeoutSeconds],[NSString stringWithFormat:@"%ld 次",(long)s.maxRetries],@""][p.row];}if(p.section==3)return [self styleName:s.translationStyle];if(p.section==4&&p.row==1)return [NSString stringWithFormat:@"%lu 条",(unsigned long)TPTermbaseManager.shared.terms.count];if(p.section==5&&p.row==3)return [NSString stringWithFormat:@"%lu 条 · %.1f KB",(unsigned long)TPCacheStore.shared.count,TPCacheStore.shared.sizeInBytes/1024.0];if(p.section==6){TPDebugLogger*l=TPDebugLogger.shared;return @[@"运行中",[NSString stringWithFormat:@"%@ · %@",l.pageState?:@"unknown",l.scanSummary?:@"尚未扫描"],TPChatPageObserver.shared.inChatPage?@"是":@"否",[l.pageState isEqualToString:@"settings"]?@"是":@"否",l.lastError?:@"无",[NSString stringWithFormat:@"%@ / %@",s.provider,s.model],[NSString stringWithFormat:@"%.2f 秒",l.lastRequestDuration],s.debugLogEnabled?@"开启":@"关闭",@""][p.row];}return @"";}
-(NSString*)styleName:(NSString*)v{NSDictionary*d=@{@"natural":@"普通自然",@"business_customer_service":@"商务客服",@"technical_sales":@"技术销售",@"short_casual":@"简短口语",@"literal":@"严谨直译"};return d[v]?:v;}
-(void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)p{[t deselectRowAtIndexPath:p animated:YES];if([self isSwitch:p])return;if(p.section==2)[self apiAction:p.row];else if(p.section==3)[self chooseStyle];else if(p.section==4&&p.row==1)[self.navigationController pushViewController:[TPTermEditor new] animated:YES];else if(p.section==5)[self cacheAction:p.row];else if(p.section==6&&p.row==8)[self.navigationController pushViewController:[TPDebugLogViewer new] animated:YES];}
-(void)apiAction:(NSInteger)row{TPSettings*s=TPSettings.shared;if(row==0){UIAlertController*a=[UIAlertController alertControllerWithTitle:@"Provider" message:nil preferredStyle:UIAlertControllerStyleActionSheet];for(NSString*v in @[@"OpenAI-compatible",@"DeepSeek",@"自定义"])[a addAction:[UIAlertAction actionWithTitle:v style:0 handler:^(id x){s.provider=v;if([v isEqualToString:@"DeepSeek"]){s.baseURL=@"https://api.deepseek.com/v1";if(!s.model.length)s.model=@"deepseek-chat";}}]];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:1 handler:nil]];[self presentViewController:a animated:YES completion:nil];return;}if(row==6){[self message:@"正在测试..."];[TPTranslationService testWithCompletion:^(NSString*r,NSError*e){[self message:r.length?r:e.localizedDescription];}];return;}NSString*title=@[@"Provider",@"Base URL",@"API Key",@"Model Name",@"超时时间（秒）",@"最大重试次数"][row];NSString*value=@[@"",s.baseURL,@"",s.model,[NSString stringWithFormat:@"%.0f",s.timeoutSeconds],[NSString stringWithFormat:@"%ld",(long)s.maxRetries]][row];[self input:title value:value secure:row==2 completion:^(NSString*v){if(row==1)s.baseURL=v;else if(row==2)[s setAPIKey:v];else if(row==3)s.model=v;else if(row==4)s.timeoutSeconds=v.doubleValue;else if(row==5)s.maxRetries=v.integerValue;}];}
-(void)chooseStyle{NSArray*values=@[@"natural",@"business_customer_service",@"technical_sales",@"short_casual",@"literal"];UIAlertController*a=[UIAlertController alertControllerWithTitle:@"翻译风格" message:nil preferredStyle:UIAlertControllerStyleActionSheet];for(NSString*v in values)[a addAction:[UIAlertAction actionWithTitle:[self styleName:v] style:0 handler:^(id x){TPSettings.shared.translationStyle=v;}]];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:1 handler:nil]];[self presentViewController:a animated:YES completion:nil];}
-(void)cacheAction:(NSInteger)r{if(r==1){[TPCacheStore.shared clearChat:TPChatPageObserver.shared.currentChatId];[self message:@"当前聊天缓存已清空"];}else if(r==2){[TPCacheStore.shared clear];[self message:@"全部缓存已清空"];}[self.tableView reloadData];}
-(void)input:(NSString*)title value:(NSString*)value secure:(BOOL)secure completion:(void(^)(NSString*))done{UIAlertController*a=[UIAlertController alertControllerWithTitle:title message:nil preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField*f){f.text=value;f.secureTextEntry=secure;f.autocapitalizationType=UITextAutocapitalizationTypeNone;}];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:1 handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"保存" style:0 handler:^(id x){done(a.textFields.firstObject.text?:@"");}]];[self presentViewController:a animated:YES completion:nil];}
-(void)message:(NSString*)text{UIAlertController*a=[UIAlertController alertControllerWithTitle:@"翻译插件" message:text?:@"未知错误" preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"好" style:0 handler:nil]];[self.presentedViewController dismissViewControllerAnimated:NO completion:^{[self presentViewController:a animated:YES completion:nil];}];}
@end
