#import "TPSettings.h"
#import <Security/Security.h>
NSString *const TPSettingsDidChangeNotification=@"TPSettingsDidChangeNotification";
static NSString *const TPService=@"com.local.translateplugin.apikey";
@implementation TPSettings
+ (instancetype)shared { static TPSettings *x; static dispatch_once_t o; dispatch_once(&o,^{x=[self new];[x load];}); return x; }
- (NSUserDefaults *)d{return NSUserDefaults.standardUserDefaults;}
- (void)load { NSUserDefaults *d=self.d; _autoTranslate=[d objectForKey:@"TPAutoTranslate"]?[d boolForKey:@"TPAutoTranslate"]:YES; _translateIncomingOnly=[d objectForKey:@"TPIncomingOnly"]?[d boolForKey:@"TPIncomingOnly"]:YES; _translateOutgoing=[d boolForKey:@"TPTranslateOutgoing"]; _showTranslationPrefix=[d objectForKey:@"TPShowPrefix"]?[d boolForKey:@"TPShowPrefix"]:YES; _showRetryOnFailure=[d objectForKey:@"TPShowRetry"]?[d boolForKey:@"TPShowRetry"]:YES; _autoScanVisibleMessages=[d objectForKey:@"TPAutoScan"]?[d boolForKey:@"TPAutoScan"]:YES; _skipChineseMessages=[d objectForKey:@"TPSkipChinese"]?[d boolForKey:@"TPSkipChinese"]:YES; _enableCache=[d objectForKey:@"TPEnableCache"]?[d boolForKey:@"TPEnableCache"]:YES; _enableTermbase=[d objectForKey:@"TPEnableTermbase"]?[d boolForKey:@"TPEnableTermbase"]:YES; _debugLogEnabled=[d boolForKey:@"TPDebugLog"]; _timeoutSeconds=[d doubleForKey:@"TPTimeout"]?:15; _maxRetries=[d objectForKey:@"TPRetries"]?[d integerForKey:@"TPRetries"]:2; _translationPrefix=[d stringForKey:@"TPPrefix"]?:@"译文："; _targetLanguage=[d stringForKey:@"TPTarget"]?:@"zh-CN"; _sourceLanguage=@"auto"; _provider=[d stringForKey:@"TPProvider"]?:@"OpenAI-compatible"; _baseURL=[d stringForKey:@"TPBaseURL"]?:@""; _model=[d stringForKey:@"TPModel"]?:@""; _translationStyle=[d stringForKey:@"TPStyle"]?:@"business_customer_service"; }
- (void)save:(id)value key:(NSString*)key { if(value)[self.d setObject:value forKey:key]; else [self.d removeObjectForKey:key]; [NSNotificationCenter.defaultCenter postNotificationName:TPSettingsDidChangeNotification object:self]; }
#define TP_BOOL_SETTER(name,ivar,defaultsKey) -(void)set##name:(BOOL)v{_##ivar=v;[self save:@(v) key:defaultsKey];}
TP_BOOL_SETTER(AutoTranslate,autoTranslate,@"TPAutoTranslate") TP_BOOL_SETTER(TranslateIncomingOnly,translateIncomingOnly,@"TPIncomingOnly") TP_BOOL_SETTER(TranslateOutgoing,translateOutgoing,@"TPTranslateOutgoing") TP_BOOL_SETTER(ShowTranslationPrefix,showTranslationPrefix,@"TPShowPrefix") TP_BOOL_SETTER(ShowRetryOnFailure,showRetryOnFailure,@"TPShowRetry") TP_BOOL_SETTER(AutoScanVisibleMessages,autoScanVisibleMessages,@"TPAutoScan") TP_BOOL_SETTER(SkipChineseMessages,skipChineseMessages,@"TPSkipChinese") TP_BOOL_SETTER(EnableCache,enableCache,@"TPEnableCache") TP_BOOL_SETTER(EnableTermbase,enableTermbase,@"TPEnableTermbase") TP_BOOL_SETTER(DebugLogEnabled,debugLogEnabled,@"TPDebugLog")
#define TP_STR_SETTER(name,ivar,defaultsKey) -(void)set##name:(NSString*)v{_##ivar=[v copy];[self save:v key:defaultsKey];}
TP_STR_SETTER(TranslationPrefix,translationPrefix,@"TPPrefix") TP_STR_SETTER(TargetLanguage,targetLanguage,@"TPTarget") TP_STR_SETTER(Provider,provider,@"TPProvider") TP_STR_SETTER(BaseURL,baseURL,@"TPBaseURL") TP_STR_SETTER(Model,model,@"TPModel") TP_STR_SETTER(TranslationStyle,translationStyle,@"TPStyle")
- (void)setSourceLanguage:(NSString*)v{_sourceLanguage=@"auto";}
- (void)setTimeoutSeconds:(NSTimeInterval)v{_timeoutSeconds=MAX(5,MIN(60,v));[self save:@(_timeoutSeconds) key:@"TPTimeout"];}
- (void)setMaxRetries:(NSInteger)v{_maxRetries=MAX(0,MIN(5,v));[self save:@(_maxRetries) key:@"TPRetries"];}
- (NSMutableDictionary*)keychainQuery{return [@{(__bridge id)kSecClass:(__bridge id)kSecClassGenericPassword,(__bridge id)kSecAttrService:TPService,(__bridge id)kSecAttrAccount:@"default"}mutableCopy];}
- (NSString*)apiKey{NSMutableDictionary*q=self.keychainQuery;q[(__bridge id)kSecReturnData]=@YES;q[(__bridge id)kSecMatchLimit]=(__bridge id)kSecMatchLimitOne;CFTypeRef out=NULL;if(SecItemCopyMatching((__bridge CFDictionaryRef)q,&out)!=errSecSuccess)return @"";return [[NSString alloc]initWithData:CFBridgingRelease(out) encoding:NSUTF8StringEncoding]?:@"";}
- (void)setAPIKey:(NSString*)key{NSMutableDictionary*q=self.keychainQuery;SecItemDelete((__bridge CFDictionaryRef)q);if(key.length){q[(__bridge id)kSecValueData]=[key dataUsingEncoding:NSUTF8StringEncoding];SecItemAdd((__bridge CFDictionaryRef)q,NULL);}[NSNotificationCenter.defaultCenter postNotificationName:TPSettingsDidChangeNotification object:self];}
- (void)resetDefaults{NSArray*keys=@[@"TPAutoTranslate",@"TPIncomingOnly",@"TPTranslateOutgoing",@"TPShowPrefix",@"TPShowRetry",@"TPAutoScan",@"TPSkipChinese",@"TPEnableCache",@"TPEnableTermbase",@"TPDebugLog",@"TPTimeout",@"TPRetries",@"TPPrefix",@"TPTarget",@"TPProvider",@"TPBaseURL",@"TPModel",@"TPStyle"];for(NSString*k in keys)[self.d removeObjectForKey:k];[self load];[NSNotificationCenter.defaultCenter postNotificationName:TPSettingsDidChangeNotification object:self];}
@end
