#import "TPTranslationRenderer.h"
#import "TPSettings.h"
#import "TPRetryController.h"
#import <objc/runtime.h>
static const void*TPStateKey=&TPStateKey,*TPLabelKey=&TPLabelKey,*TPMessageKey=&TPMessageKey;
@implementation TPTranslationRenderer
+(TPBubbleState)stateForCell:(UIView*)cell{return [objc_getAssociatedObject(cell,TPStateKey)integerValue];}
+(UIView*)container:(UIView*)cell{if([cell isKindOfClass:UITableViewCell.class])return ((UITableViewCell*)cell).contentView;if([cell isKindOfClass:UICollectionViewCell.class])return ((UICollectionViewCell*)cell).contentView;return cell;}
+(UILabel*)labelForMessage:(TPExtractedMessage*)m{UILabel*l=objc_getAssociatedObject(m.cell,TPLabelKey);if(!l){l=[UILabel new];l.accessibilityIdentifier=@"tp.translation";l.numberOfLines=0;l.font=[UIFont systemFontOfSize:11];l.userInteractionEnabled=NO;l.layer.cornerRadius=4;l.clipsToBounds=YES;UIView*c=[self container:m.cell];c.clipsToBounds=NO;[c addSubview:l];objc_setAssociatedObject(m.cell,TPLabelKey,l,OBJC_ASSOCIATION_RETAIN_NONATOMIC);}UIView*c=[self container:m.cell];CGRect sr=[m.sourceView convertRect:m.sourceView.bounds toView:c];CGFloat available=MAX(120,CGRectGetWidth(c.bounds)-24);CGFloat maxWidth=MIN(MAX(140,CGRectGetWidth(sr)),available);CGSize fit=[l sizeThatFits:CGSizeMake(maxWidth,52)];CGFloat h=MIN(52,MAX(18,fit.height+5));CGFloat x=m.outgoing?MAX(12,CGRectGetMaxX(sr)-maxWidth):MAX(12,CGRectGetMinX(sr));CGFloat desiredY=CGRectGetMaxY(sr)+2;CGFloat y=MIN(desiredY,MAX(1,CGRectGetHeight(c.bounds)-h-1));l.frame=CGRectMake(MAX(4,MIN(x,CGRectGetWidth(c.bounds)-maxWidth-4)),y,maxWidth,h);l.autoresizingMask=UIViewAutoresizingFlexibleTopMargin|(m.outgoing?UIViewAutoresizingFlexibleLeftMargin:UIViewAutoresizingFlexibleRightMargin);[c bringSubviewToFront:l];return l;}
+(void)style:(UILabel*)l failed:(BOOL)failed{if(@available(iOS 13,*)){l.textColor=failed?UIColor.systemRedColor:UIColor.secondaryLabelColor;l.backgroundColor=UIColor.secondarySystemBackgroundColor;}else{l.textColor=failed?UIColor.redColor:UIColor.grayColor;l.backgroundColor=[UIColor colorWithWhite:.95 alpha:.92];}}
+(void)setState:(TPBubbleState)state message:(TPExtractedMessage*)m text:(NSString*)text{objc_setAssociatedObject(m.cell,TPStateKey,@(state),OBJC_ASSOCIATION_RETAIN_NONATOMIC);objc_setAssociatedObject(m.cell,TPMessageKey,m.messageId,OBJC_ASSOCIATION_COPY_NONATOMIC);UILabel*l=[self labelForMessage:m];l.text=text;[self style:l failed:state==TPBubbleStateFailed];l.userInteractionEnabled=state==TPBubbleStateFailed;[self labelForMessage:m];}
+(void)setTranslatingForMessage:(TPExtractedMessage*)m{[self setState:TPBubbleStateTranslating message:m text:@"正在翻译..."];}
+(void)setTranslation:(NSString*)t forMessage:(TPExtractedMessage*)m{NSString*value=TPSettings.shared.showTranslationPrefix?[TPSettings.shared.translationPrefix stringByAppendingString:t]:t;[self setState:TPBubbleStateTranslated message:m text:value];}
+(void)setFailure:(NSError*)e forMessage:(TPExtractedMessage*)m retry:(dispatch_block_t)retry{if(!TPSettings.shared.showRetryOnFailure){[self resetCell:m.cell];return;}[self setState:TPBubbleStateFailed message:m text:@"翻译失败，点击重试"];UILabel*l=objc_getAssociatedObject(m.cell,TPLabelKey);[TPRetryController attachRetry:retry toLabel:l cell:m.cell];}
+(void)resetCell:(UIView*)cell{UILabel*l=objc_getAssociatedObject(cell,TPLabelKey);[l removeFromSuperview];objc_setAssociatedObject(cell,TPLabelKey,nil,OBJC_ASSOCIATION_RETAIN_NONATOMIC);objc_setAssociatedObject(cell,TPStateKey,@(TPBubbleStateUnprocessed),OBJC_ASSOCIATION_RETAIN_NONATOMIC);objc_setAssociatedObject(cell,TPMessageKey,nil,OBJC_ASSOCIATION_COPY_NONATOMIC);}
@end
