#import "TPUIInjector.h"
#import "TPTranslationService.h"
#import "TPSettings.h"
#import "TPMessageScanner.h"
@interface TPUIInjector()<UIGestureRecognizerDelegate>
@property(nonatomic,weak) UITextView *composer;
@property(nonatomic,strong) UIButton *button;
@property(nonatomic,weak) UIView *scanRoot;
@property(nonatomic,strong) NSTimer *scanTimer;
@end
@implementation TPUIInjector
+(instancetype)shared{static id x;static dispatch_once_t o;dispatch_once(&o,^{x=[self new];});return x;}
- (void)walk:(UIView*)v textViews:(NSMutableArray*)a { if([v isKindOfClass:UITextView.class] && !v.hidden && v.window) [a addObject:v]; for(UIView *s in v.subviews)[self walk:s textViews:a]; }
- (void)scanFrom:(UIViewController*)vc { if(!vc.view.window)return; NSMutableArray *a=[NSMutableArray array]; [self walk:vc.view textViews:a]; UITextView *best=nil; for(UITextView *t in a) if(!best || CGRectGetMinY([t convertRect:t.bounds toView:nil])>CGRectGetMinY([best convertRect:best.bounds toView:nil])) best=t; if(!best || CGRectGetHeight(best.bounds)>180)return; self.composer=best; self.scanRoot=vc.view; [self attachButtonTo:best]; [self attachLongPressIn:vc.view]; [self startScanning]; }
+- (void)startScanning { if(!self.scanTimer){ self.scanTimer=[NSTimer scheduledTimerWithTimeInterval:1.2 target:self selector:@selector(scanMessages) userInfo:nil repeats:YES]; } [self scanMessages]; }
+- (void)scanMessages { UIView *root=self.scanRoot; UITextView *composer=self.composer; if(root.window&&composer.window)[TPMessageScanner.shared scanVisibleMessagesInView:root excludingComposer:composer]; }
- (void)attachButtonTo:(UITextView*)t { if(self.button.superview==t.superview)return; [self.button removeFromSuperview]; UIButton *b=[UIButton buttonWithType:UIButtonTypeSystem]; self.button=b; b.accessibilityLabel=@"TranslatePlugin 翻译"; [b setTitle:@"译" forState:UIControlStateNormal]; b.titleLabel.font=[UIFont boldSystemFontOfSize:16]; b.backgroundColor=[UIColor colorWithWhite:0.92 alpha:0.95]; b.layer.cornerRadius=17; [b addTarget:self action:@selector(translateComposer) forControlEvents:UIControlEventTouchUpInside]; UIView *p=t.superview; [p addSubview:b]; b.translatesAutoresizingMaskIntoConstraints=NO; [NSLayoutConstraint activateConstraints:@[[b.widthAnchor constraintEqualToConstant:34],[b.heightAnchor constraintEqualToConstant:34],[b.trailingAnchor constraintEqualToAnchor:t.trailingAnchor constant:-4],[b.centerYAnchor constraintEqualToAnchor:t.centerYAnchor]]]; t.textContainerInset=UIEdgeInsetsMake(t.textContainerInset.top,t.textContainerInset.left,t.textContainerInset.bottom,40); }
- (void)translateComposer { UITextView *t=self.composer; NSString *original=t.text; if(!original.length)return; self.button.enabled=NO; [self.button setTitle:@"…" forState:UIControlStateNormal]; [TPTranslationService translate:original completion:^(NSString *r,NSError *e){ self.button.enabled=YES; [self.button setTitle:@"译" forState:UIControlStateNormal]; if(r.length){ t.text=r; [t.delegate textViewDidChange:t]; } else [self alert:e.localizedDescription ?: @"翻译失败"]; }]; }
- (void)attachLongPressIn:(UIView*)root { if(root.accessibilityIdentifier && [root.accessibilityIdentifier containsString:@"tp.longpress"])return; root.accessibilityIdentifier=[(root.accessibilityIdentifier?:@"") stringByAppendingString:@" tp.longpress"]; UILongPressGestureRecognizer *g=[[UILongPressGestureRecognizer alloc]initWithTarget:self action:@selector(longPress:)]; g.cancelsTouchesInView=NO; g.delegate=self; [root addGestureRecognizer:g]; }
- (BOOL)gestureRecognizer:(UIGestureRecognizer*)g shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer*)o{return YES;}
- (UILabel*)labelAt:(CGPoint)p in:(UIView*)v { UIView *hit=[v hitTest:p withEvent:nil]; while(hit){ if([hit isKindOfClass:UILabel.class] && ((UILabel*)hit).text.length)return (UILabel*)hit; for(UIView *s in hit.subviews)if([s isKindOfClass:UILabel.class]&&((UILabel*)s).text.length)return (UILabel*)s; hit=hit.superview;} return nil; }
- (void)longPress:(UILongPressGestureRecognizer*)g { if(g.state!=UIGestureRecognizerStateBegan)return; UILabel *l=[self labelAt:[g locationInView:g.view] in:g.view]; if(!l.text.length)return; UIAlertController *a=[UIAlertController alertControllerWithTitle:@"翻译消息" message:l.text preferredStyle:UIAlertControllerStyleActionSheet]; [a addAction:[UIAlertAction actionWithTitle:@"翻译" style:0 handler:^(id x){[TPTranslationService translate:l.text completion:^(NSString*r,NSError*e){if(r)[self result:r];else[self alert:e.localizedDescription];}];}]]; [a addAction:[UIAlertAction actionWithTitle:@"复制原文" style:0 handler:^(id x){UIPasteboard.generalPasteboard.string=l.text;}]]; [a addAction:[UIAlertAction actionWithTitle:@"取消" style:1 handler:nil]]; [self.top presentViewController:a animated:YES completion:nil]; }
- (UIViewController*)top { UIWindow *w; for(UIWindow *x in UIApplication.sharedApplication.windows)if(x.isKeyWindow)w=x; UIViewController *v=w.rootViewController; while(v.presentedViewController)v=v.presentedViewController; if([v isKindOfClass:UINavigationController.class])v=((UINavigationController*)v).topViewController; return v; }
- (void)result:(NSString*)r { UIPasteboard.generalPasteboard.string=r; UIAlertController*a=[UIAlertController alertControllerWithTitle:@"译文（已复制）" message:r preferredStyle:1];[a addAction:[UIAlertAction actionWithTitle:@"好" style:0 handler:nil]];[self.top presentViewController:a animated:YES completion:nil]; }
- (void)alert:(NSString*)s {[self result:s?:@"未知错误"];}
@end
